title: Paolo Diviacco's Homepage
page-top-title: Paolo Diviacco
top-section-bg-text: Open Science, Open Data
home-subtitle: Paolo Diviacco
copyright-text: '&copy; Paolo Diviacco 2026. All Rights Reserved.'
